"""Your migration message

Revision ID: fca5444ef527
Revises: 4ec0dabee30d
Create Date: 2024-04-01 15:31:24.378621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca5444ef527'
down_revision = '4ec0dabee30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.drop_index('oprtr_employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.create_index('oprtr_employee_id', ['oprtr_employee_id'], unique=True)

    # ### end Alembic commands ###
